"""
IT Automation Incident Ticket Manager
--------------------------------------
Laboratory Activity 1: Linear Data Structures

This program simulates how support teams organize and manage incident
tickets generated by automation bots. It uses a LIST (a linear data
structure) to store tickets, where each ticket is represented as a
dictionary with three fields: Incident ID, Bot, and Short Description.

Supported operations:
    1. Add a new incident ticket
    2. Display all active incident tickets
    3. Search for a ticket by Incident ID
    4. Remove a resolved ticket
    5. Display the total number of active tickets
"""

# ------------------------------------------------------------------
# The linear data structure: a list of ticket records.
# Each record is a dictionary: {"id": ..., "bot": ..., "desc": ...}
# ------------------------------------------------------------------
tickets = []


def add_ticket(incident_id, bot, description, silent=False):
    """Add a new incident ticket to the list."""
    # Prevent duplicate Incident IDs
    for t in tickets:
        if t["id"].upper() == incident_id.upper():
            if not silent:
                print(f"\n[ERROR] Ticket {incident_id} already exists.\n")
            return False

    ticket = {"id": incident_id, "bot": bot, "desc": description}
    tickets.append(ticket)  # append = insert at the end of the linear list

    if not silent:
        print(f"\n[OK] Ticket {incident_id} added successfully.\n")
    return True


def display_tickets():
    """Display all active incident tickets currently in the list."""
    print("\n" + "=" * 90)
    print("ACTIVE INCIDENT TICKETS")
    print("=" * 90)

    if len(tickets) == 0:
        print("No active incident tickets.")
    else:
        print(f"{'Incident ID':<15}{'Bot':<20}{'Short Description'}")
        print("-" * 90)
        # Traverse the list from beginning to end (linear traversal)
        for t in tickets:
            print(f"{t['id']:<15}{t['bot']:<20}{t['desc']}")

    print("=" * 90 + "\n")


def search_ticket(incident_id):
    """Search for a ticket by Incident ID using linear search."""
    for index, t in enumerate(tickets):  # linear search: one-by-one scan
        if t["id"].upper() == incident_id.upper():
            print("\n[FOUND] Ticket located:")
            print(f"   Position in list : {index}")
            print(f"   Incident ID      : {t['id']}")
            print(f"   Bot              : {t['bot']}")
            print(f"   Description      : {t['desc']}\n")
            return t

    print(f"\n[NOT FOUND] No ticket with Incident ID '{incident_id}' exists.\n")
    return None


def remove_ticket(incident_id):
    """Remove a resolved ticket from the list by Incident ID."""
    for index, t in enumerate(tickets):
        if t["id"].upper() == incident_id.upper():
            tickets.pop(index)  # remove element at that position
            print(f"\n[OK] Ticket {incident_id} marked resolved and removed.\n")
            return True

    print(f"\n[ERROR] Cannot remove. Ticket '{incident_id}' not found.\n")
    return False


def count_tickets():
    """Display the total number of active incident tickets."""
    print(f"\nTotal active incident tickets: {len(tickets)}\n")
    return len(tickets)


def load_sample_data():
    """Preload the 10 sample incident tickets given in the activity."""
    sample_data = [
        ("INC1392939", "BOT-Inventory", "Failed to generate the daily report"),
        ("INC1392940", "BOT-Email", "Failed to send the scheduled notification"),
        ("INC1392941", "BOT-DataSync", "Encountered an error during data transfer"),
        ("INC1392942", "BOT-Invoice", "Failed to process an invoice"),
        ("INC1392943", "BOT-Report", "Failed to generate the weekly report"),
        ("INC1392944", "BOT-FileTransfer", "Failed to upload the required file"),
        ("INC1392945", "BOT-DataEntry", "Encountered an error while entering records"),
        ("INC1392946", "BOT-Backup", "Failed to complete the scheduled backup"),
        ("INC1392947", "BOT-Validation", "Failed to validate the submitted records"),
        ("INC1392948", "BOT-Notification", "Failed to send the system alert"),
    ]
    for incident_id, bot, desc in sample_data:
        add_ticket(incident_id, bot, desc, silent=True)
    print(f"\n[OK] Loaded {len(sample_data)} sample incident tickets.\n")


def run_demo():
    """
    Demonstrates each required operation automatically, in order:
    adding, displaying, searching, removing, and counting.
    This satisfies the requirement to test the program with the
    10 sample tickets and demonstrate every operation.
    """
    print("\n" + "#" * 90)
    print("DEMONSTRATION MODE: showing all required operations")
    print("#" * 90)

    # 1. Adding tickets (load the 10 sample tickets)
    print("\n--- 1. ADDING TICKETS ---")
    load_sample_data()

    # Also demonstrate adding one brand-new ticket
    add_ticket("INC1392999", "BOT-Scheduler", "Failed to trigger the nightly job")

    # 2. Displaying tickets
    print("--- 2. DISPLAYING TICKETS ---")
    display_tickets()

    # 3. Searching for a ticket
    print("--- 3. SEARCHING FOR A TICKET ---")
    search_ticket("INC1392944")
    search_ticket("INC0000000")  # not found example

    # 4. Removing a resolved ticket
    print("--- 4. REMOVING A RESOLVED TICKET ---")
    remove_ticket("INC1392940")
    display_tickets()

    # 5. Counting active tickets
    print("--- 5. COUNTING ACTIVE TICKETS ---")
    count_tickets()

    print("#" * 90)
    print("END OF DEMONSTRATION")
    print("#" * 90 + "\n")


def print_menu():
    print("=" * 50)
    print(" IT AUTOMATION INCIDENT TICKET MANAGER")
    print("=" * 50)
    print("1. Add a new incident ticket")
    print("2. Display all active incident tickets")
    print("3. Search for a ticket by Incident ID")
    print("4. Remove a resolved ticket")
    print("5. Display total number of active tickets")
    print("6. Load the 10 sample tickets")
    print("7. Run full demonstration (all operations)")
    print("0. Exit")
    print("=" * 50)


def main():
    while True:
        print_menu()
        choice = input("Enter your choice: ").strip()

        if choice == "1":
            incident_id = input("Enter Incident ID: ").strip()
            bot = input("Enter Bot name: ").strip()
            desc = input("Enter Short Description: ").strip()
            add_ticket(incident_id, bot, desc)

        elif choice == "2":
            display_tickets()

        elif choice == "3":
            incident_id = input("Enter Incident ID to search: ").strip()
            search_ticket(incident_id)

        elif choice == "4":
            incident_id = input("Enter Incident ID to remove: ").strip()
            remove_ticket(incident_id)

        elif choice == "5":
            count_tickets()

        elif choice == "6":
            load_sample_data()

        elif choice == "7":
            run_demo()

        elif choice == "0":
            print("\nExiting program. Goodbye!\n")
            break

        else:
            print("\n[ERROR] Invalid choice. Please try again.\n")


if __name__ == "__main__":
    main()
